language: ruby
before_install:
  - gem install bundler --pre
bundler_args: --without development
script: "script/test_all"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head
  # - rbx-18mode
  # - rbx-19mode
notifications:
  email:
    - boy.maas@gmail.com
