#!/bin/bash

relevant_ruby_versions=(1.9.2 1.9.3 ree jruby 1.8.7)

source script/colored_echo.sh

set -e

function install_ruby_environment() {
  ruby_version="$1"
  rvm install $ruby_version
}

function install_and_run_with() {
  ruby_version="$1"
  rvm_gemset="${ruby_version}@syma"

  source $(rvm $rvm_gemset --create do rvm env --path) 

  (rvm current | grep -q $ruby_version)
  if [ "$?" -ne "0" ]; then 
    echo "Problem setting up rvm environment for $rvm_gemset" 
    return 0
  fi


  colored_echo $bldblu "In rvm environment $bldred$(rvm current)"
  colored_echo $bldblu "Cleaning gemset and installing bundle"
  rvm gemset clear $rvm_gemset
  gem install bundler --pre
  bundle 
  test_all
}

function test_all() {
  bundle exec rspec spec 1>/dev/null

  for file in `find spec -iname '*_spec.rb'`; do
    echo "Running $file"
    bundle exec rspec $file 
  done
}

if [ "$1" == "prepare" ]; then
  colored_echo $bldred "Installing ruby environment $1"

  for ruby_version in "${relevant_ruby_versions[@]}"
  do
    install_ruby_environment $ruby_version
  done
  exit 0
fi


if [ "$1" == "all" ]; then
  colored_echo $bldred "Executing tests on single ruby environment $1"

  for ruby_version in "${relevant_ruby_versions[@]}"
  do
    install_and_run_with $ruby_version
  done
  exit 0
fi

if [ -n "$1" ] ; then
  colored_echo $bldred "Executing test on single ruby environment $1"

  install_and_run_with $1
  exit 0
fi

test_all
